const app = require('../app')
const agent = require('supertest').agent(app)
const mockStation = require('./mock/station.json');
const loginAsRole = require('./helpers/loginAsRole');
const stationSearchBody = require('./mock/station_search_body.json');

let draft;

beforeAll(async (done) => {
  const townRes = await agent.get('/api/town/london');
  draft = townRes.body.drafts.find(d => d.autogenerated);
  done();
});

// SEARCH STATIONS
// POST /api/:draftId/station/search
describe('SEARCH STATIONS', () => {

  let tokenA;

  beforeAll(async (done) => {
    tokenA = await loginAsRole('A');
    done();
  });

  it('when user is not logged it can not search stations', async (done) => {
    agent.post(`/api/${draft._id}/station/search`).set('Accept', 'application/json')
      .expect(401, done);
  });

  it('when user is logged it can search stations', async (done) => {
    agent.post(`/api/${draft._id}/station/search`).send(stationSearchBody).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(200, done);
  });

  it('when body does not contain proper pagination it returns 400', async (done) => {
    agent.post(`/api/${draft._id}/station/search`).send({ ...stationSearchBody, pagination: null }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(400, done);
  });

});

// GET FULL INFO FROM STATION
// POST /api/station/:stationId
describe('GET FULL INFO FROM STATION', () => {

  let tokenA;
  let station;

  beforeAll(async (done) => {
    tokenA = await loginAsRole('A');
    const stationRes = await agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(200);
    station = stationRes.body;
    done();
  });

  it('when user is not logged it can not see station info', async (done) => {
    agent.get(`/api/station/${station._id}`).set('Accept', 'application/json')
      .expect(401, done);
  });

  it('when user is logged it can see station info', async (done) => {
    const stationRetrieved = await agent.get(`/api/station/${station._id}`).set('Accept', 'application/json').expect('Content-Type', /json/).set('Authorization', `Bearer ${tokenA}`)
      .expect(200);
    expect(stationRetrieved.body.key).toBe(station.key);
    expect(stationRetrieved.body.year).toBe(station.year);
    done();
  });

})

// ADD STATION
// POST /api/:draftId/station
describe('ADD STATION', () => {

  let tokenU;
  let tokenM1;
  let tokenA;

  beforeAll(async (done) => {
    tokenU = await loginAsRole('U');
    tokenM1 = await loginAsRole('M1');
    tokenA = await loginAsRole('A');
    done();
  });

  it('when user is not logged it can not add station', async (done) => {
    agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json')
      .expect(401, done);
  });

  it('when user is not town manager it can not add station', async (done) => {
    agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenU}`)
      .expect(401, done);
  });

  it('when user is town manager it can add station', async (done) => {
    agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM1}`)
      .expect(200, done);
  });

  it('when user is admin it can add station', async (done) => {
    agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(200, done);
  });

  it('when station does not contain name it returns bad request', async (done) => {
    agent.post(`/api/${draft._id}/station`).send({ ...mockStation, name: null }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(400, done);
  });

  it('when station does not contain geometry it returns bad request', async (done) => {
    agent.post(`/api/${draft._id}/station`).send({ ...mockStation, geometry: 'test station' }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(400, done);
  });

  it('when station year is not a valid value it returns bad request', async (done) => {
    agent.post(`/api/${draft._id}/station`).send({ ...mockStation, year: 2050 }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`)
      .expect(400, done);
  });

});

// UPDATE STATION
// PUT /api/station/:stationId
describe('UPDATE STATION', () => {

  let tokenM1;
  let tokenM2;
  let tokenA;
  let station;

  beforeAll(async (done) => {
    tokenM1 = await loginAsRole('M1');
    const stationRes = await agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM1}`).expect(200);
    station = stationRes.body;
    done();
  });

  it('when user is creator it can update station', async (done) => {
    const modifedStationRes = await agent.put(`/api/station/${station._id}`).send({ ...mockStation, name: 'New station name' }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM1}`).expect(200);
    expect(modifedStationRes.body.name).toBe('New station name');
    done();
  });

  it('when user is not creator it can not update station', async (done) => {
    tokenM2 = await loginAsRole('M2');
    agent.put(`/api/station/${station._id}`).send({ ...mockStation, name: 'New station name' }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM2}`).expect(401, done);
  });

  it('when user is admin it can update station', async (done) => {
    tokenA = await loginAsRole('A');
    const modifedStationRes = await agent.put(`/api/station/${station._id}`).send({ ...mockStation, name: 'New station name' }).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenA}`).expect(200);
    expect(modifedStationRes.body.name).toBe('New station name');
    done();
  });
});

// DELETE STATION
// DELETE /api/station/:stationId
describe('DELETE STATION', () => {

  let tokenM1;
  let tokenM2;
  let tokenA;
  let station1;
  let station2;

  beforeAll(async (done) => {
    tokenM1 = await loginAsRole('M1');
    const stationRes1 = await agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM1}`).expect(200);
    station1 = stationRes1.body;
    const stationRes2 = await agent.post(`/api/${draft._id}/station`).send(mockStation).set('Accept', 'application/json').set('Authorization', `Bearer ${tokenM1}`).expect(200);
    station2 = stationRes2.body;
    done();
  });

  it('when user is creator it can delete station', async (done) => {
    await agent.delete(`/api/station/${station1._id}`).set('Authorization', `Bearer ${tokenM1}`).expect(200);
    agent.get(`/api/station/${station1._id}`).set('Authorization', `Bearer ${tokenM1}`).expect(404, done);
  });

  it('when user is not creator it can not delete station', async (done) => {
    tokenM2 = await loginAsRole('M2');
    agent.delete(`/api/station/${station2._id}`).set('Authorization', `Bearer ${tokenM2}`).expect(401, done);
  });

  it('when user is admin it can delete station', async (done) => {
    tokenA = await loginAsRole('A');
    await agent.delete(`/api/station/${station2._id}`).set('Authorization', `Bearer ${tokenA}`).expect(200);
    agent.get(`/api/station/${station2._id}`).set('Authorization', `Bearer ${tokenA}`).expect(404, done);
  });
});